[project]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "image-db-to-ome"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
jupyterlab = ">=4.4.6,<5"

[pypi-dependencies]
ome-zarr = ">=0.12.2, <0.13"
tifffile = ">=2025.8.28, <2026"
ome-types = ">=0.6.1, <0.7"
